### ISSUE TITLE
Feature request: matching and reverse

### ISSUE THREAD

**Issue by nvcnvn** [jtacoma/uritemplates#2]
Its would be handy if we can match and extract value from an url, for example:

template, _ := uritemplates.Parse("api.github.com/repos{/user,repo}")
agrs := make(map[string]interface{})
if template.Match("api.github.com/repos/jtacoma/uritemplates", args) {
    fmt.Println(map["user"]) // jtacoma
    fmt.Println(map["repo"]) // uritemplates
}

**Comment by jtacoma** [comment]
Alright, I like the idea, but I'm going to close this for now.  If anybody wants to propose a way to deal with ambiguities in the reverse mapping from URI through pattern to map (or struct), please feel free to write another issue with those details.
