### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by aviau** [jtacoma/uritemplates#9]
> / Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

Do you consider MIT a BSD-style license? Or was there another license before?

**Comment by jtacoma** [comment]
Oops... I made this mistake in 2b6fc855d3a722bc0e5525ae50bb3c10703c5450 where I intended to switch to the same license nearly all Go packages use, which is a BSD license.  Interesting that nobody else noticed this.
